module: CaffeineKit
author: jrr6

swift_version: 5.2.4
min_acl: public

output: docs
clean: true

docset_icon: logo.png
author_url: https://jrr6.github.io
github_url: https://github.com/jrr6/CaffeineKit
root_url: https://jrr6.github.io/CaffeineKit/

copyright: 'Copyright &copy; 2021 jrr6. CaffeineKit is made available under the [MIT License](https://github.com/jrr6/CaffeineKit/blob/master/LICENSE).'
theme: apple

github_file_prefix: https://github.com/jrr6/CaffeineKit/tree/v0.3.2
module_version: 0.3.2
