module: CaffeineKit
author: aaplmath

min_acl: public
swift_version: 4.2

output: docs
clean: true

docset_icon: logo.png
author_url: https://aaplmath.github.io
github_url: https://github.com/aaplmath/CaffeineKit
root_url: https://aaplmath.github.io/CaffeineKit/

copyright: 'Copyright &copy; 2018 aaplmath. CaffeineKit is made available under the [MIT License](https://github.com/aaplmath/CaffeineKit/blob/master/LICENSE).'
theme: apple

github_file_prefix: https://github.com/aaplmath/CaffeineKit/tree/v0.1.0
module_version: 0.1.0
